### ISSUE TITLE
get_post_single_term_html がなくなって Fatal error が発生する

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-term-color#4]
https://vws.vektor-inc.co.jp/forums/topic/vk-blocks-pro-1-60-0-0-get_post_single_term_html-fatal-error

https://github.com/vektor-inc/vk-term-color/commit/b70bff5ecef317ac057b5f281b4a8f338dbc0a14 のコミットで削除になっている

**Comment by kurudrive** [comment]
@mthaichi 
これって https://github.com/vektor-inc/vk-term-color/commit/b70bff5ecef317ac057b5f281b4a8f338dbc0a14 の変更理由って何です（・ｗ・？
一応把握しておかないとメソッド復活して別の問題発生したらまずいなと思いまして（・ｗ・

**Comment by mthaichi** [comment]
> @mthaichi これって [b70bff5](https://github.com/vektor-inc/vk-term-color/commit/b70bff5ecef317ac057b5f281b4a8f338dbc0a14) の変更理由って何です（・ｗ・？ 一応把握しておかないとメソッド復活して別の問題発生したらまずいなと思いまして（・ｗ・

@kurudrive 今となってはなぜかわかりませんが、メソッドを削った記憶は無いので、単なるミスで削られたように思われます。しかも内部で参照しているものを削っているので、ありえないミスですね。すみません。

メソッド復活して発生する問題はどんなことが考えられますか？  あまり外部からは参照されていないように見えます。
念入りに調べた上で、修正致します。申し訳ございません。

**Comment by mthaichi** [comment]
@kurudrive  直しましたので、ご確認くださいませ。
get_auto_post_single_term_html()も削除されていたので復活させました。
そのような使われ方をしていることを知らず、外部のどこからも参照されていないので、削除してしまったかもしれません。申し訳ございません。

**Comment by kurudrive** [comment]
ありがとうございました。closeしますー！
